
// <auto-generated>
//     This code was generated by the update builder generator tool.
//     Changes to this file may cause incorrect behavior and will be lost if  the code is regenerated.

using System;
using Optional;

namespace SourceGeneratorApp
{
    public class ClientUpdateBuilder
    {

        private SourceGeneratorApp.ClientId _id;

        private Optional.Option<string> _name;

        private bool _changesMade;

        public ClientUpdateBuilder(ClientId id)
        {
            _id = id;
        }

        public ClientUpdateBuilder UpdateName(string name)
        {
            return UpdateField(() => _name = Option.Some(name));
        }

        public Option<ClientUpdate> Build()
                    => _changesMade
                        ? Option.Some(BuildUpdate())
                        : Option.None<ClientUpdate>();

        private ClientUpdateBuilder UpdateField(Action updateField)
        {
            updateField();
            _changesMade = true;
            return this;
        }

        private ClientUpdate BuildUpdate()
            => new ClientUpdate(
                _id,
				_name);
    }
}
    => new ClientUpdate(
                _id,
				_name);
    }
}
